CREATE DATABASE PRUEBA
GO

USE PRUEBA
GO

CREATE TABLE TIPO_DOCUMENTO(
ID INT PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL
)

CREATE TABLE CLIENTE(
ID INT PRIMARY KEY IDENTITY(1,1),
PNOMBRE VARCHAR(20) NOT NULL,
SNOMBRE VARCHAR(20),
PAPELLIDO VARCHAR(20) NOT NULL,
SAPELLIDO VARCHAR(20),
TIPO_DOC INT FOREIGN KEY REFERENCES TIPO_DOCUMENTO(ID) NOT NULL,
NUM_DOC VARCHAR(15) NOT NULL,
)

CREATE TABLE UINMOBILIARIA (
ID INT PRIMARY KEY IDENTITY(1,1),
TIPO VARCHAR(50) NOT NULL,
NOMENCLATURA VARCHAR(100) NOT NULL,
VALOR FLOAT NOT NULL,
AREA FLOAT
)

CREATE TABLE UNIDADES_CLIENTE(
ID_UNIDAD INT FOREIGN KEY REFERENCES UINMOBILIARIA(ID),
ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID)
)